# Generated by Django 4.2.3 on 2023-07-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type_pet', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('size', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('image_pet', models.ImageField(upload_to='static/images/pets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
